import {ServerErrors} from "./constants.ts";
export const validationTexts: any = {
    requireMap: 'Privalote pasirinkti vietą žemėlapyje',
    requirePhotos: 'Privalote įkelti nuotrauką',
    userDeniedLocation: 'Turite leisti nustatyti jūsų buvimo vietą',
    requireSpeciesType: 'Privalote pasirinkti bent vieną rūšių tipą',
    requireText: 'Privalomas laukelis',
    requireSelect: 'Privalote pasirinkti',
    badEmailFormat: 'Blogas el. pašto adresas',
    badPhoneFormat: 'Blogai įvestas telefono numeris',
    tooFrequentRequest: 'Nepavyko, per dažna užklausa prašome pabandyti veliau ',
    passwordsDoNotMatch: 'Slaptažodžiai nesutampa',
    error: 'Įvyko nenumatyta klaida, prašome pabandyti vėliau',
    validFirstName: 'Įveskite taisyklingą vardą',
    validLastName: 'Įveskite taisyklingą pavardę',
    [ServerErrors.WRONG_PASSWORD]: 'Blogas elektroninis paštas arba slaptažodis',
    [ServerErrors.USER_NOT_FOUND]: 'Naudotojo su tokiu el. paštu nėra',
    badFileTypes: 'Blogi failų tipai',
    fileSizesExceeded: 'Viršyti failų dydžiai',
    personalCode: 'Neteisingas asmens kodo formatas',
    positiveNumber: 'Reikšmė turi būti didesnė už nulį',
    requireFiles: 'Privalote įkelti dokumentus',
    atLeastOneColumn: 'Turi būti pasirinktas bent vienas stulpelis',
};
