name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  deploy-staging:
    name: Deploy staging
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Staging
      docker-image: ghcr.io/AplinkosMinisterija/biip-zvejyba-web
      enable-sentry: true
      build-args: |
        NODE_ENV=production
        VITE_SENTRY_ENV=staging
        VITE_SENTRY_DSN=https://0fadf707c6574ab792a4dd2f8d729ea2@sentry.biip.lt/42
